name: Deploy E-commerce

on:
  push:
    branches: [master]

env:
  DOCKER_IMAGE: fahernkhan/ecommerce-app
  DOCKER_TAG: latest
  AWS_EC2_HOST: ${{ secrets.AWS_EC2_HOST }}
  SSH_USER: ubuntu

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.AWS_EC2_HOST }}
          username: ${{ env.SSH_USER }}
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
            docker-compose down
            docker-compose up -d
            docker exec ecommerce-app npx prisma migrate deploy